
name = "worldforge-archivist-v3-3"
main = "workers/archivist/index.mjs"
compatibility_date = "2024-06-10"

[vars]
ENV = "stg"

[[kv_namespaces]]
binding = "WF_KV_STAGING"
id = "KV_STAGING_ID"

[[kv_namespaces]]
binding = "WF_KV_CANON"
id = "KV_CANON_ID"

[[kv_namespaces]]
binding = "WF_KV_ARCHIVE"
id = "KV_ARCHIVE_ID"

[[kv_namespaces]]
binding = "WF_NOMINA_SETS"
id = "KV_NOMINA_SETS_ID"

[[kv_namespaces]]
binding = "WF_NOMINA_STATS"
id = "KV_NOMINA_STATS_ID"

[[kv_namespaces]]
binding = "WF_RNG_ROLLS"
id = "KV_RNG_ROLLS_ID"
